name: Kubernetes set context

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set context (Service account approach)
        id: setcontext_sa
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_API_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SA }}
      -
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: 'olympus'
          manifests: |
              manifests/deployment.yaml
              manifests/service.yaml
          # images: 'hello-world:latest'
          # imagepullsecrets: |
          #   image-pull-secret1
          #   image-pull-secret2
          kubectl-version: 'latest'
