name: Kubernetes set context

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Kubeconfig approach
      #   id: setcontext_kc
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: <your kubeconfig> # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
      #     context: <context name>  #If left unspecified, current-context from kubeconfig is used as default
      -
        #
        # For fetching Server URL, execute the following command on your shell:
        # kubectl config view --minify -o 'jsonpath={.clusters[0].cluster.server}'
        #
        # For fetching Secret object required to connect and authenticate with the cluster, the following sequence of commands need to be run:
        # kubectl get serviceAccounts <service-account-name> -n <namespace> -o 'jsonpath={.secrets[*].name}'
        # kubectl get secret <service-account-secret-name> -n <namespace> -o yaml
        #
        name: Service account approach
        id: setcontext_sa
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_API_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SA_TOKEN }}
